### ISSUE TITLE
[Dev] Back End Mutation for Add Property

### ISSUE THREAD

**Issue by ryanrightmer** [open-austin/BASTA-tfwa#131]
# Description

Need to create/update mutation for adding properties to align with required data and existing interface from front end. This will be mostly backend, but the frontend will need to be updated to use the new-ish mutation.

# Acceptance Criteria

- You can create a new property from the front end

# Who should I contact?

@cdpadilla42 @JamesBock 

# Size of Ticket

M

Additional Notes: 

Please specify the associated work domain:
- Dev-Frontend
- Dev-Backend
- Dev-Infrastructure
- Dev-Fullstack

**Comment by minpat** [comment]
I'll be using branch pm/131 for this.  Thanks.

**Comment by minpat** [comment]
Hi @JamesBock - could you please let me know if I'm ok to close this ticket?  Thanks.

**Comment by JamesBock** [comment]
> Hi @JamesBock - could you please let me know if I'm ok to close this ticket? Thanks.
Closed
