### ISSUE TITLE
[Dev] Update Automatic Type Generation

### ISSUE THREAD

**Issue by ryanrightmer** [open-austin/BASTA-tfwa#136]
# Description

We need to be running https://github.com/apollographql/apollo-tooling#apollo-clientcodegen-output essentially every time we start the React development server. i.e. `npm start` should have something along the lines of `apollo client:codegen  --endpoint=https://api.dev.tenantfile.org/graphql`. That is not a working example, more parameters are required to support typescript etc. 

# Wireframes

Include any relevant wireframes here

# Acceptance Criteria

- README needs to be updated with instructions of what to do if you are making server changes locally and want to change how the code is generated
- Every run of the React app should run the generation script prior to starting

# Dev Notes

- Very carefully read all of the options in https://github.com/apollographql/apollo-tooling#apollo-clientcodegen-output

# Who should I contact?

@ryanrightmer 

# Size of Ticket

S

**Comment by rixong** [comment]
After installing Apollo/Tools globally:
`npm install -g apollo`
I ran the following which seemed to do the trick. Note that I stored the output inside of src/types.
`apollo client:codegen ./src/types --target=typescript --localSchemaFile=graphql-schema.json --outputFlat`

This begs another question - where is **graphql-schema.json** coming from? I think there's a way to automatically regenerate this file from the API as well. I'll do more research.

**Comment by rixong** [comment]
I deleted the global.ts file that was generated as it doesn't seemed to be needed as of yet and throws a TS error.

**Comment by rixong** [comment]
Update - client:codegen is pulling gql schema from graphql-schema.json. In order to update the schema from the API, we can run in terminal:
`apollo client:download-schema tenant-file/portal-app/graphql-schema.json --endpoint=https://api.dev.tenantfile.org/graphql`
