### ISSUE TITLE
Images not going to correct storage bucket folders

### ISSUE THREAD

**Issue by JamesBock** [open-austin/BASTA-tfwa#81]
Our code for uploading images and thumbnails to cloud storage is prepending the folder name to the file name instead of adding the images to the appropriate folders. This seems to be happening due to the Path.Combine field, DefaultCharSeperator, being a backslash on Windows, which just makes the folder path become part of the file name in storage. This shouldn't be a problem if the code is run on a system where forward slash is the default (anything but Windows, basically) but it should work in any situation.

**Comment by ryanrightmer** [comment]
Oooh, I didn't think about Windows. You're right that it should always be a backslash since the only OS that matters is the one that firebase is using.

**Comment by JamesBock** [comment]
I have a fix for it in the .Net5  repo I've been working on. The official release date is nov 10 so we should be ready to upgrade everything as soon as its released.

**Comment by ryanrightmer** [comment]
Yeah, we can pend on this until then.
